### ISSUE TITLE
AttributeError: module 'community' has no attribute 'modularity'

### ISSUE THREAD

**Issue by lzicar1** [saibalmars/GraphRicciCurvature#36]
> AttributeError                            Traceback (most recent call last)
> [<ipython-input-630-2f096ba7f28d>](https://localhost:8080/#) in <module>()
> ----> 1 cc = orc_football.ricci_community()
> 
> 2 frames
> [/usr/local/lib/python3.7/dist-packages/GraphRicciCurvature/OllivierRicci.py](https://localhost:8080/#) in ricci_community(self, cutoff_step, drop_threshold)
>     838         """
>     839 
> --> 840         cc = self.ricci_community_all_possible_clusterings(cutoff_step=cutoff_step, drop_threshold=drop_threshold)
>     841         assert cc, "No clustering found!"
>     842 
> 
> [/usr/local/lib/python3.7/dist-packages/GraphRicciCurvature/OllivierRicci.py](https://localhost:8080/#) in ricci_community_all_possible_clusterings(self, cutoff_step, drop_threshold)
>     882         logger.info("Ricci flow detected, start cutting graph into community...")
>     883         cut_guesses = \
> --> 884             get_rf_metric_cutoff(self.G, weight=self.weight, cutoff_step=cutoff_step, drop_threshold=drop_threshold)
>     885         assert cut_guesses, "No cutoff point found!"
>     886 
> 
> [/usr/local/lib/python3.7/dist-packages/GraphRicciCurvature/util.py](https://localhost:8080/#) in get_rf_metric_cutoff(G_origin, weight, cutoff_step, drop_threshold)
>      96         clustering = {c: idx for idx, comp in enumerate(nx.connected_components(G)) for c in comp}
>      97         # Compute modularity
> ---> 98         modularity.append(community_louvain.modularity(clustering, G, weight))
>      99 
>     100     good_cuts = []
> 
> AttributeError: module 'community' has no attribute 'modularity'

Calling function ricci_community() has some problem (trying to replicate the tutorial notebook). Maybe the solution is simply this? [STACK OVERFLOW Attribute error community has no attribute](https://stackoverflow.com/questions/53017174/attributeerror-module-networkx-algorithms-community-has-no-attribute-best-pa)

**Comment by saibalmars** [comment]
Solved in https://github.com/saibalmars/GraphRicciCurvature/pull/39/commits/0e67e5119fe0617b46ae9ced5523857cd26b6b38

Thanks for the info.

**Comment by pollytur** [comment]
I still face the same issue (installed from scratch on Colab )

```
orc = OllivierRicci(G, alpha=0.5, verbose="INFO")
orc.ricci_community()
```

Traceback

```
INFO:GraphRicciCurvature:Ricci flow not detected yet, run Ricci flow with default setting first...
INFO:GraphRicciCurvature:No ricciCurvature detected, compute original_RC...
INFO:GraphRicciCurvature:0.258078 secs for Ricci curvature computation.
INFO:GraphRicciCurvature: === Ricci flow iteration 0 === 
INFO:GraphRicciCurvature:0.335991 secs for Ricci curvature computation.
INFO:GraphRicciCurvature: === Ricci flow iteration 1 === 
INFO:GraphRicciCurvature:0.604810 secs for Ricci curvature computation.
INFO:GraphRicciCurvature: === Ricci flow iteration 2 === 
INFO:GraphRicciCurvature:0.650828 secs for Ricci curvature computation.
INFO:GraphRicciCurvature: === Ricci flow iteration 3 === 
INFO:GraphRicciCurvature:0.727168 secs for Ricci curvature computation.
INFO:GraphRicciCurvature: === Ricci flow iteration 4 === 
INFO:GraphRicciCurvature:0.528388 secs for Ricci curvature computation.
INFO:GraphRicciCurvature: === Ricci flow iteration 5 === 
INFO:GraphRicciCurvature:0.370375 secs for Ricci curvature computation.
INFO:GraphRicciCurvature: === Ricci flow iteration 6 === 
INFO:GraphRicciCurvature:0.247215 secs for Ricci curvature computation.
INFO:GraphRicciCurvature: === Ricci flow iteration 7 === 
INFO:GraphRicciCurvature:0.199036 secs for Ricci curvature computation.
INFO:GraphRicciCurvature: === Ricci flow iteration 8 === 
INFO:GraphRicciCurvature:0.204243 secs for Ricci curvature computation.
INFO:GraphRicciCurvature: === Ricci flow iteration 9 === 
INFO:GraphRicciCurvature:0.269540 secs for Ricci curvature computation.
INFO:GraphRicciCurvature:4.716530 secs for Ricci flow computation.
INFO:GraphRicciCurvature:Ricci flow detected, start cutting graph into community...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-39-bb6b5f15049b>](https://msl7zy2js3-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230718-060202-RC00_548938380#) in <cell line: 1>()
----> 1 orc.ricci_community()

2 frames
[/usr/local/lib/python3.10/dist-packages/GraphRicciCurvature/OllivierRicci.py](https://msl7zy2js3-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230718-060202-RC00_548938380#) in ricci_community(self, cutoff_step, drop_threshold)
    838         """
    839 
--> 840         cc = self.ricci_community_all_possible_clusterings(cutoff_step=cutoff_step, drop_threshold=drop_threshold)
    841         assert cc, "No clustering found!"
    842 

[/usr/local/lib/python3.10/dist-packages/GraphRicciCurvature/OllivierRicci.py](https://msl7zy2js3-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230718-060202-RC00_548938380#) in ricci_community_all_possible_clusterings(self, cutoff_step, drop_threshold)
    882         logger.info("Ricci flow detected, start cutting graph into community...")
    883         cut_guesses = \
--> 884             get_rf_metric_cutoff(self.G, weight=self.weight, cutoff_step=cutoff_step, drop_threshold=drop_threshold)
    885         assert cut_guesses, "No cutoff point found!"
    886 

[/usr/local/lib/python3.10/dist-packages/GraphRicciCurvature/util.py](https://msl7zy2js3-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230718-060202-RC00_548938380#) in get_rf_metric_cutoff(G_origin, weight, cutoff_step, drop_threshold)
     96         clustering = {c: idx for idx, comp in enumerate(nx.connected_components(G)) for c in comp}
     97         # Compute modularity
---> 98         modularity.append(community_louvain.modularity(clustering, G, weight))
     99 
    100     good_cuts = []

AttributeError: module 'community' has no attribute 'modularity'
```
